### ISSUE TITLE
BPASS "numbers" files

### ISSUE THREAD

**Issue by JJEldridge** [HeloiseS/hoki#1]
I don't think the current version of hoki works with the numbers files. I try to make a plot of O stars vs time and get a weird output and when I try to print the values of the number of O stars or ages I get something that looks like this:

"                            log_age  ...  WC_lL
NaN 0 . 6 0 0 0 0 0 0 E + 0 1 NaN 0 . 1 7 8 2 3 9 9 E + 0 4 NaN 0 . 2 3 7 2 2 1 6 E + 0 3 NaN 0 . 5 6 4 9 6 4 8 E + 0 1 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 4 4 3 3 4 5 6 E - 0 2 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 1 6 5 7 2 6 0 E + 0 4 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 3 4 2 4 8 6 4 E + 0 5 NaN 0 . 2 5 0 7 5 9 1 E + 0 5 NaN 0 . 1 8 3 2 7 8 8 E + 0 6 NaN 0 . 2 0 7 1 1 5 9 E + 0 6 NaN 0 . 6 7 7 7 5 7 8 E + 0 6 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 0 0 0 0 0        0  ...    NaN
          1 0 0 0 0 0 E + 0 1 NaN 0 . 1 8 3 6 1 1 8 E + 0 4 NaN 0 . 2 5 7 1 9 0 1 E + 0 3 NaN 0 . 2 1 9 5 9 4 4 E + 0 2 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 0 0 0 0 0 0 0 E + 0 0 NaN 0 . 0 0 0 "

My guess is that columns are getting confused or the code doesn't like NaNs!

**Comment by HeloiseS** [comment]
Thanks JJ - what number file were you using and what version of pandas are you running ? 

It works on my machine and I try it so either it's a pandas version thing or it's because there is something going on with that particular file!

**Comment by HeloiseS** [comment]
The separator in the loading routine was r\s* which worked for me but caused your code to load individual characters instead. By replacing this separators by r\s+ the issue was fixed.

This will be fixed in pypi soon and is already working on the GitHub version.
