### ISSUE TITLE
Make funciton to convert BPASS spectra to real units - Spectrum class needed?

### ISSUE THREAD

**Issue by HeloiseS** [HeloiseS/hoki#14]
I need a function that converts BPASS spectra to observer units. 

Depending on what i end up doing with my spectra I might need to make a Spectra(BPASSObject) class.

**Comment by HeloiseS** [comment]
Just to summarise what @maxbriel  and I discussed yesterday for the record:

The BPASSspectrum classe would be a utility to help easily manipulate *single BPASS spectra* and turn them into observer units, modify distances, smooth, etc... for data analysis purposes.

This is will not be written as a object to use in wide applications that require speed and a large number of spectra to be processed. In these instances, `hoki` will rely on existing Python libraries such as `numpy`

**Comment by findesgh** [comment]
Can't `astropy.units` do this for you?
