### ISSUE TITLE
Table of Content missing pages

### ISSUE THREAD

**Issue by maxbriel** [HeloiseS/hoki#15]
The ToC is missing the AgeWizard when accessing sub-pages. The AgeWizard page is not visible from any of the sub-pages, such as Transient Rates, HR Diagrams, ..., Colour Magnitide diagrams.

The "intro.html" and "index.html" page do show AgeWizard, but the former also shows several sub-headers as main pages. Maybe this is intentional?

**Comment by HeloiseS** [comment]
Try emptying your browser cache - that should help fix the problem

**Comment by maxbriel** [comment]
Sadly that's not the solution. 

I think it might be internal caching in sphinx. It doesn't rebuild old pages, even if the TOC has changed. Emptying the build directory and rebuilding the docs should solve this issue. Maybe?

I tried to do this myself, but could not run the sphynx build command due to a missing `conf.py` file.

**Comment by HeloiseS** [comment]
okay - I'll make a note of that. Sphynx will recreate pages if you use the touch .rst command but it;s not always consistent. 
Next time I update the docs I'll make a fresh compile. 

As for sphynx, you don't have the source, you don't have the source so you won't be able to compile it.

**Comment by HeloiseS** [comment]
Hey Max,

as I did the migration i also took the time to fix the docs. it looks fine for me but can you double check it looks fine on your browser?

cheers,
Heloise

**Comment by maxbriel** [comment]
This looks good now! Solved!
