### ISSUE TITLE
Update to v2.2.2 stellar model files with Gaia magnitudes

### ISSUE THREAD

**Issue by JJEldridge** [HeloiseS/hoki#16]
Can we please update hoki to be able to read new stellar model files which include Gaia filters and some expanded HST filters. The new list of files, new stellar model files and new constants.py file is here: https://drive.google.com/open?id=1DrdIaPKl9X_JZpfcOj6jwD6Qe4JVr81p

Although hoki will need to be updated to be able to pick up either the old number of columns (93) or the number of columns (114).

Thank you!

**Comment by HeloiseS** [comment]
added this option to branch `dummy_dictionary_versioning` :)
