### ISSUE TITLE
default BPASS version is 221. Can't use filters from 222

### ISSUE THREAD

**Issue by glebgeinke** [HeloiseS/hoki#21]
**HokiKeyError: One or both of the chosen filters do not correspond to a valid filter key. from cmd.py**

Try/except checks filters against columns in **self.dummy_dict[key]**, where 
-        **self.dummy_dict=dummy_dicts[bpass_version]**
and 
-       **bpass_version=DEFAULT_BPASS_VERSION** (which is set to v221 in settings.yaml)

Just changing that to v222 helps

**Comment by glebgeinke** [comment]
Here is the file I ran that was giving the error

[GAIA_M67.zip](https://github.com/HeloiseS/hoki/files/4656332/GAIA_M67.zip)

**Comment by HeloiseS** [comment]
did you change the bpass_version to 'v222' when you call the object? you really need to do that if you want to be able to use bpass v2.2.2. You can also cahnge your default bpass version if you want

**Comment by glebgeinke** [comment]
Ohhh I only just realise that I could've just added it in the argument, my
bad! Yes, I just changed the default. Thank you though, that was a but dumb
of me xD

**Comment by HeloiseS** [comment]
ain't nothing dumb about learning ;)
