### ISSUE TITLE
[DOCS] Tutorial links point to old location

### ISSUE THREAD

**Issue by maxbriel** [HeloiseS/hoki#37]
Links to tutorials in the docs are not linked to the correct location. 

On the following pages:
- HR diagram
- Spectra
- CMD
- AgeWizard

**Suggestion to improve or clear confusion:**
Replace links with https://github.com/HeloiseS/hoki_tutorials

This is an issue in the `hoki` docs and in the `hoki_tutorials` repository

**Comment by HeloiseS** [comment]
i fixed it but for some reason the gh-pages branch doesn't seem to have updated although I pushed. 

review after 24 hours to see if the changes  worked

**Comment by HeloiseS** [comment]
it worked, yeah
