### ISSUE TITLE
Question Regarding BPASS models

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#41]
Do the BPASS binary stellar population models used for Hoki include single stars? This is since in the BPASS v2.2 release paper it is stated that "In BPASS v2.2 we implement a new set of weighting parameters for binary fraction, period and mass ratio dis-
tribution, as a function of the mass of the primary star. We base our new binary parameter distribution on those deter-
mined by the detailed study of Moe & Di Stefano (2017, hereafter MS17) . . ." (Stanway et. al 2018).

**Comment by HeloiseS** [comment]
The binary models include a realistic fraction of binary stars so *yes* there will be single stars in that population! You can check if a model is single or not by checking the "type": -1 is single :D

**Comment by HeloiseS** [comment]
let me know if this answers your question or close the issue :)

**Comment by RyotaInagaki1** [comment]
This answered my question. Thank you very much.
