### ISSUE TITLE
[BPASS] Data Types in the individual stellar models

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#45]
In which specific columns of the .dat files representing the BPASS stellar models may there be non floating point values? What do those non-floating point values signify physically?
From,
Ryota Inagaki

**Comment by HeloiseS** [comment]
you might find `inf` in some columns 

to solve this problem I recommend pandas utilities: `pd.to_numeric([my_series], errors='coerce')`

**Comment by RyotaInagaki1** [comment]
For the NEWSEC stellar evolution models, I believe that there may be -inf or inf in the columns, correct? Are there
 any black holes or neutron stars or invisible secondaries in the binary stellar models?
