### ISSUE TITLE
[BPASS] HR diagrams - unresolved or resolved binaries?

### ISSUE THREAD

**Issue by sunnc** [HeloiseS/hoki#47]
Hi, I see with HOKI one can plot HR diagrams of single or binary stellar populations. How are the binaries treated in the HR diagrams? Is a binary system considered as an unresolved object on the diagram or as two stars that can be located in different parts of the diagram?

I guess it's the latter since the HR diagrams use parameters of logTe or logG, which can only be defined for individual stars, not for unresolved binaries. However, unresolved binaries seem to be more common in astronomy. So I'm confused.

Thank you!

**Comment by HeloiseS** [comment]
Thanks for your patience!! Here is Jan Eldridge's answer :)

_Each star in a binary are treated at separate points on the diagram. In the instrument paper we do plot eclipsing binaries on the page like this. Although this is "okay" as in the cases where you can't tell if there is a companion or not the secondary will be in a completely different part of the HR diagram._

_However the CMDs are different here we do plot stars/binaries as a single object as they're done from your code. Although the treatment of secondaries here might be a bit problematic but it's something we're dealing with in future._
