### ISSUE TITLE
[BPASS] Meaning of Timestep

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#49]
What is the physical meaning of the timestep in stellar models?
Thank You,
Ryota Inagaki

**Comment by HeloiseS** [comment]
it's just a number - the stellar models don't actually record all the time steps - only the ones where something new and interesting happens! this is too avoid to have files that are unsustainably large :) You shouldn't need to use the timestep number as a user, you can just use age
