### ISSUE TITLE
[BPASS] Phases of individual stellar models?

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#51]
Is there a 1 to 1 and user accessible mapping from stellar model to the phase (pre-main sequence, main sequence, white dwarf, black hole, neutron star, etc.) in the BPASS stellar model and stellar population directories?

**Comment by HeloiseS** [comment]
no.

To determine whether a model is a white dwarf  an MS star or a giant you need to check the surface gravity.

For black holes and neutron stars you need to pair the BPASS models with TUI. for more details, you can directly contact j.eldridge@auckland.ac.nz

**Comment by RyotaInagaki1** [comment]
Are black holes and neutron stars in the individual BPASS Stellar evolution models?

**Comment by HeloiseS** [comment]
if you are asking whether black holes and neutron stars are modelled by BPASS, they are not. 
I strongly recommend taking a look at the instrument paper: https://ui.adsabs.harvard.edu/abs/2017PASA...34...58E/abstract
