### ISSUE TITLE
[BPASS] Non-visible compact remnants

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#55]
For the NEWSEC stellar evolution models, I believe that there may be -inf or inf in the columns, correct? Are the compact remnant primaries reflected in the quantity M2 for the NewSec models?
Are neutron stars and black holes visible in the individual stellar evolution models?
And although it may be ridiculous to ask, is it true that none of the single star or primary stars in the NEWBINMODS models in BPASS are non-visible remnants (neutron star, black hole)?

**Comment by HeloiseS** [comment]
there can be infinity values in some columns in the stellar models. - to get a proper remnant (NS or BH) then another code called TUI is required - contact Jan Eldridge for more detail. 
And the remnants depend on initial mass - low mass stars can become white dwarfs so not all remnants will be NS or BH
