### ISSUE TITLE
Age Wizard Name Issue

### ISSUE THREAD

**Issue by aaltm** [HeloiseS/hoki#65]
When loading data, if the name of stars have spacing and other symbols within the string, error when initializing Age Wizard. 
<img width="526" alt="Screen Shot 2020-10-21 at 12 25 22 PM" src="https://user-images.githubusercontent.com/69299301/96654800-94f56900-1398-11eb-9de8-dff911b5e7bd.png">
 

**To Reproduce**
File attached to Reproduce.

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by HeloiseS** [comment]
could you send me the jupyter notebook again that causes the issue? Cheers

**Comment by HeloiseS** [comment]
it's been fixed in v1.6 :)
