### ISSUE TITLE
[BPASS] hmg files and naming convention

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#66]
Are all QHE-binary BPASS evolution models in the subdirectories of NEWSINMODS that are named in the format of <metallicity>hmg?
Also, to be extra sure, should I look at the Age=0.0 years value of the M2 value of the evolution model to find the initial secondary star mass of the hmg models?

**Comment by HeloiseS** [comment]
hi!

Sorry what do you mean by hmg format?

**Comment by RyotaInagaki1** [comment]
I meant files in the NEWSINMODS directory that are in metallicity subdirectories with suffix hmg (e.g. files in directories such as /bpass-v2.2-newmodels/NEWSINMODS/z001hmg from the BPASS v2.2.1 data package.).

**Comment by HeloiseS** [comment]
yes - the QHE models are in NEWSINMOD, remember that when BPASS simulates binary evolution not *all* stars are binaries, it also contains single stars :)

**Comment by RyotaInagaki1** [comment]
So are all QHE binary models single stars or stars that have merged? Or do the QHE models contain a combination of both merged binaries and non-merged binaries?

**Comment by JanJEldridge** [comment]
The HMG/QHE files are just made by assuming they're fully mixed why hydrogen burning is going on. The are only selected in the BPASS population at metallicitiy mass fraction less than or equal to 0.004, at masses of 20Msun and they are secondaries which accrete more than 5% of their initial mass. Mergers are in the primary models if the modeltypes = 0 and extra mixing is not included for those in the current release.

**Comment by RyotaInagaki1** [comment]
I should have worded my question a bit more clearly: are QHE models single star models or does the binary QHE secondary model come with a primary? In other words, when dealing with HMG/QHE models, should I bother to use the values in the binary parameters like M2, log10(R2), log10(T2)? Or should I treat the QHE models as single stars?

**Comment by JanJEldridge** [comment]
They are effectively treated as single stars. However in the population synthesis for working out GW transient event rates the models are used to work out how a QHE+BH system evolves. As the QHE star only gets smaller during it's evolution if the stars aren't interacting at birth they won't interact afterwards. But as mass-loss in stellar winds affecting the orbit it's an easy calculation to do. But otherwise the stellar models themselves are just single stars.
