### ISSUE TITLE
[DOCS] Spelling Error: 'developped' on What is Hoki page? 

### ISSUE THREAD

**Issue by BriannaGopaul** [HeloiseS/hoki#67]
**Issue:** 
Spelling Error: "In order to facilitate the application of BPASS to a wide range of scientific investigations, we have [developped] the tools necessary "

**Location:** 
The second paragraph on [this page](https://heloises.github.io/hoki/intro.html#built-with-data-analysis-in-mind). 

**Fix:** 
[developped] --> [developed]

**Comment by HeloiseS** [comment]
Thanks!! will be fixed in v1.6 that is coming up  now :)
