### ISSUE TITLE
[BPASS] Regarding NEWSECMODS

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#69]
Dear Dr. Stevance and Dr. Eldridge,
I am wondering why the NEWSECMODS start at age 0.0 since, intuitively, stars do not start their lifetimes as compact remnants. **How do I get the true initial (ZAMS) masses of the NEWSECMODS model's primary and companion?**
Thank You,
Ryota Inagaki
**(Edited)**

**Comment by JanJEldridge** [comment]
Hi Ryota,
yes good question and this is something that is lacking in the current release and the treatment is quite approximate. This is also discussed in both the original 2009 paper as well as the 2017 instrument paper. 

The thing is multiple primary models can given rise to secondary models, it's not a one to one relation. If you look at the input files this does also for each primary model give a "mixed age" which takes account any rejuvenation of the secondary star when it accretes material from the primary, however this is a mean age so again is approximate.

We do have a new version of the population synthesis that does a better job of linking the primary models to the secondary models fixing the issue of working out which primary models give the secondary models. It's in the form of a new input file which I could provide depending on what you're working for as this is a "beta" data product and not a full release yet.

Long term we are hoping that in v3.0 we'll link the primary and secondary models together and remove this artefact of starting the secondary models at zero age but that is still some time away. The reason this was originally done by the way is just to try to be efficient with computing time, although in the last 5 years that is no longer such a problem.

Thanks,

Jan.

**Comment by RyotaInagaki1** [comment]
As for the input file, it already have an IMF imposed on it?

**Comment by RyotaInagaki1** [comment]
I would like to beta-testing the new data product. Please send documentation with information on how to find the exact primary and secondary initial mass using the data product, and please contact me at ryotainagaki@berkeley.edu.
Also, is there a pre-imposed IMF on it?
Thank You,
Ryota Inagaki

**Comment by HeloiseS** [comment]
Hi Ryota,

There is a `mixed_imf` to take into account for the rejuvinated whereas the other models have a `model imf` in the input file. 
This discussion looks like a specific discussion regarding an upcoming feature so I'm going to close this issue and suggestion the convo carries on through email to discuss unreleased data products :)

Thanks for you questions!

Cheers,
Heloise
