### ISSUE TITLE
[BPASS] Failed installation of hoki

### ISSUE THREAD

**Issue by palfeng** [HeloiseS/hoki#70]
Hello, 

I tried to install BPASS following the command: sudo -H pip3 install --user hoki
It seems like the installation is good, but unfortunately I cannot import hoki after the installation. I tried several times in different conda environment, but all failed. I am appreciated if you can help!

Xinfeng

System: macOS, Mojave, v10.14
Log:

(BPASS2) Macintosh-4:python3.7 xuxinfeng$ sudo -H pip3 install --user hoki
Collecting hoki
  Downloading hoki-1.5.1.tar.gz (62.7 MB)
     |████████████████████████████████| 62.7 MB 26.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: wheel in /Users/xuxinfeng/anaconda/envs/BPASS2/lib/python3.7/site-packages (from hoki) (0.36.2)
Collecting corner
  Downloading corner-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: setuptools>=40.6.0 in /Users/xuxinfeng/anaconda/envs/BPASS2/lib/python3.7/site-packages (from corner->hoki) (51.0.0.post20201207)
Collecting matplotlib
  Downloading matplotlib-3.3.3-cp37-cp37m-macosx_10_9_x86_64.whl (8.5 MB)
     |████████████████████████████████| 8.5 MB 19.9 MB/s 
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/xuxinfeng/anaconda/envs/BPASS2/lib/python3.7/site-packages (from matplotlib->hoki) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /Users/xuxinfeng/anaconda/envs/BPASS2/lib/python3.7/site-packages (from matplotlib->hoki) (2.8.1)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: six in /Users/xuxinfeng/anaconda/envs/BPASS2/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->hoki) (1.15.0)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp37-cp37m-macosx_10_9_x86_64.whl (61 kB)
     |████████████████████████████████| 61 kB 15.6 MB/s 
Collecting numpy
  Downloading numpy-1.19.4-cp37-cp37m-macosx_10_9_x86_64.whl (15.3 MB)
     |████████████████████████████████| 15.3 MB 36.5 MB/s 
Collecting pillow>=6.2.0
  Downloading Pillow-8.0.1-cp37-cp37m-macosx_10_10_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 63.0 MB/s 
Collecting emcee
  Downloading emcee-3.0.2-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 2.0 MB/s 
Collecting pandas
  Downloading pandas-1.1.5-cp37-cp37m-macosx_10_9_x86_64.whl (10.0 MB)
     |████████████████████████████████| 10.0 MB 35.8 MB/s 
Collecting pytz>=2017.2
  Downloading pytz-2020.4-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 38.1 MB/s 
Collecting pysynphot
  Downloading pysynphot-1.0.0.tar.gz (10.8 MB)
     |████████████████████████████████| 10.8 MB 58.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting astropy
  Downloading astropy-4.2-cp37-cp37m-macosx_10_9_x86_64.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 18.9 MB/s 
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 34.7 MB/s 
Collecting soupsieve>1.2
  Downloading soupsieve-2.1-py3-none-any.whl (32 kB)
Collecting pyerfa
  Downloading pyerfa-1.7.1.1-cp37-cp37m-macosx_10_9_x86_64.whl (304 kB)
     |████████████████████████████████| 304 kB 47.3 MB/s 
Collecting pyyaml
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 37.2 MB/s 
Collecting setuptools-scm
  Using cached setuptools_scm-5.0.1-py2.py3-none-any.whl (28 kB)
Building wheels for collected packages: hoki, pysynphot, pyyaml
  Building wheel for hoki (PEP 517) ... done
  Created wheel for hoki: filename=hoki-1.5.1-py3-none-any.whl size=46275217 sha256=9d4e39a5d173b6f46bc135681b0fa90a683703f3ace99422efc936bb59bc62e5
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/38/82/d7/449dbfceba1a71b7c4925df341f6ebd90b2e3ded866f6b70d1
  Building wheel for pysynphot (PEP 517) ... done
  Created wheel for pysynphot: filename=pysynphot-1.0.0-cp37-cp37m-macosx_10_9_x86_64.whl size=6688690 sha256=a68563d501a8273d610f41146f6da9944cce9b2fef57e78407ea617dc7f33304
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/45/54/e5/ded461804aa36e39001f9bfc4867261b47834c437a3c85e69d
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp37-cp37m-macosx_10_9_x86_64.whl size=44626 sha256=1406a471a7319b44faa02a858e33f93c2988360e4147443aa1e7919e22733f4b
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
Successfully built hoki pysynphot pyyaml
Installing collected packages: numpy, soupsieve, pyerfa, pillow, kiwisolver, cycler, setuptools-scm, pytz, matplotlib, beautifulsoup4, astropy, pyyaml, pysynphot, pandas, emcee, corner, hoki
  WARNING: The scripts f2py, f2py3 and f2py3.7 are installed in '/var/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
  WARNING: The scripts fits2bitmap, fitscheck, fitsdiff, fitsheader, fitsinfo, samp_hub, showtable, volint and wcslint are installed in '/var/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
  WARNING: The script astropy-package-template-example is installed in '/var/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Successfully installed astropy-4.2 beautifulsoup4-4.9.3 corner-2.1.0 cycler-0.10.0 emcee-3.0.2 hoki-1.5.1 kiwisolver-1.3.1 matplotlib-3.3.3 numpy-1.19.4 pandas-1.1.5 pillow-8.0.1 pyerfa-1.7.1.1 pysynphot-1.0.0 pytz-2020.4 pyyaml-5.3.1 setuptools-scm-5.0.1 soupsieve-2.1

(BPASS2) Macintosh-4:python3.7 xuxinfeng$ python
Python 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hoki
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hoki'
>>> exit()

**Comment by maxbriel** [comment]
Hi palfeng!

Thank you for your message! Annoying that `hoki` does not want to install in your environment. While I have an idea what is going on, I need some more information to be able to provide a solution.

1. How have you setup your conda environment? (what commands)
2. Have you installed an new instance of `pip` within your "BPASS2" environment?
3. Have you tried the installation using `pip install hoki` within you conda environment?

When in an environment it is not recommended to use `--user` when installing packages. This and `sudo` might be what are causing your issue with the installation. It's most likely installing `hoki` outside your environment. 

As a possible solution: 
1. Within your environment run `pip install hoki`. If this did not run successfully, go to 3.
2. To verify if the installation succeeded, run `conda list` and check if `hoki` is in the list.
3. If not on the list, install a new instance of `pip` from outside the environment: `conda install -n BPASS2 pip`
4. Activate your environment again and retry to install `hoki` using `pip install hoki`

Please let me know about the questions and if the possible solution works or how far you were able to get with the steps.

Kind regards,
Max

**Comment by palfeng** [comment]
Thanks Max, I finished all 4 steps and now hoki is correctly installed! 

Thanks a lot!

Cheers,
Xinfeng
