### ISSUE TITLE
[BPASS] BPASS Time Bins For Stellar System Models

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#71]
Do BPASS time bins apply for the individual stellar system models? In other words, are BPASS stellar system models (i.e. the files that are in HOKI.MODELS_PATH) meant to hold information for just the ages in the range 6.0 <= log10(age) <= 11.0?
I am asking this since the HOKI CMD.py uses time bins (for 6.0, 6.1, ..., 11.0 in log10(age)) even though it directly accesses the BPASS stellar system models.

**Comment by HeloiseS** [comment]
Hi!

That's a great question. The actual stellar models do not limit themselves to the BPASS time bins and so the CMD class actually does the binning for you. That's a very important step and a rather tricky one - that's why it's automated.

Hope this helps!
