### ISSUE TITLE
Related package

### ISSUE THREAD

**Issue by findesgh** [HeloiseS/hoki#8]
I just wanted to make you aware of [this](https://gitlab.mpcdf.mpg.de/mglatzle/pybpass) little package I've written.

It's intended for people who need spectral data for large numbers of stellar particles from hydro simulations. Obviously, `hoki` aims to provide much broader functionality, but as far as I can tell it's missing this feature.

I would also not be opposed to merging things into `hoki` at some point and if you believe that would make sense.

Cheers :-).

**Comment by HeloiseS** [comment]
That's freaking cool. I'm not a hydro person so I would never have thought of that. Can you send me an email to hfstevance@gmail.com so we can talk about how to get that into hoki?

thanks for your patience - I was on holiday in February and just noticed your Issue :)

**Comment by findesgh** [comment]
See #46.
