### ISSUE TITLE
Staircase aspect of the HR diagram isocontours [DOCS] 

### ISSUE THREAD

**Issue by AlexandreLegault** [HeloiseS/hoki#88]
Plotting HR diagrams using HOKI yields isocontours that have 'staircase' shapes for lower luminosities. Is it only due to the resolution of the grid steps or does it have some physical origin?
Thanks!

**Comment by HeloiseS** [comment]
The shape of the isocontours is a result of matplotlib and the size of the grid which is `np.meshgrid(np.arange(0.1, 10.1, 0.1), np.arange(-2.9, 7.1, 0.1))` - these ranges are quoted in the BPASS manual on page 18.
